# Generated by Django 3.1.3 on 2021-01-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name_1',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='identity_document_1',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name_1',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='newrequest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_1_1',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_2_1',
            field=models.BigIntegerField(null=True),
        ),
    ]
