# Generated by Django 3.1.3 on 2021-02-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210121_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='amount',
        ),
        migrations.AddField(
            model_name='account',
            name='note',
            field=models.CharField(default='', max_length=280),
            preserve_default=False,
        ),
    ]
