# Generated by Django 3.1.3 on 2021-03-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210227_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='address',
            new_name='parent',
        ),
    ]
