# Generated by Django 3.1.3 on 2021-03-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210322_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['last_name']},
        ),
    ]
