# Generated by Django 3.1.3 on 2021-01-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='quota',
            field=models.CharField(choices=[('PAGO', 'PAGO'), ('NO PAGO', 'NO PAGO'), ('SEPARADO', 'SEPARADO')], default='PAGO', max_length=10),
        ),
    ]
