# Generated by Django 3.1.3 on 2021-02-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210223_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='amount',
        ),
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.CharField(default='', max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='recover',
            field=models.BooleanField(default=False),
        ),
    ]
