# Generated by Django 3.1.3 on 2021-03-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210227_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='onlyday',
            field=models.BooleanField(default=False),
        ),
    ]
