# Generated by Django 3.1.3 on 2021-03-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_attendance_onlyday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['student']},
        ),
    ]
